DROP ALL OBJECTS;
CREATE TABLE PRICES(ID  BIGINT,BRAND_ID BIGINT,START_DATE TIMESTAMP,END_DATE TIMESTAMP,PRICE_LIST BIGINT,PRODUCT_ID BIGINT,PRIORITY INTEGER,PRICE DOUBLE PRECISION,CURR VARCHAR(255));

